// HTTP Status Codes
export enum HttpStatus {
  // Success
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,

  // Client Errors
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  GONE = 410,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,

  // Server Errors
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
}

export enum JwtError {
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
}

export enum JwtAudience {
  PLATFORM = "platform",
  TENANT = "tenant",
}

export enum AccountError {
  ACCOUNT_PERMANENTLY_DELETED = "ACCOUNT_PERMANENTLY_DELETED",
  IDENTITY_CONFLICT = "IDENTITY_CONFLICT",
}
